[build]
  command = "next dev"
  publish = ".next"

  [functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "next dev"
  targetPort = 3000
  port = 8888
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
