
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto  } from "next/font/google";
import "./globals.css";
import './cover.carousel.css'
import './globalCustome.css'
import React from 'react';
import  Navbar  from '../app/navigationbar/page'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const RobotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['100', '400', '600', '900'],
});

export const metadata: Metadata = {
  title: "Aperture Abhijit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable} ${RobotoFont.variable}`}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
